server:
  port: 9040
  
spring:
  application:
    name: gateway
  cloud:
    config:
      name: redis,eureka_client
      profile: dev
      label: master
      uri: http://localhost:8760/
      fail-fast: true
      discovery:
        enabled: true # 表示开启通过服务名来访问config-server
        service-id: config-server # 表示注册中心config-server的服务名