server:
  port: 7901
spring: 
  jpa:
    gennerate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    datasource:
      platform: h2
      schema: 
        classpath: schema.sql
      data: 
        classpath: data.sql
  application:
    name: songmm-consumer
eureka: 
  client: 
    service-url: 
      defaultZoon: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    HelloFeignService#get():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 1000
        
        
