server:
  port: 7902
spring: 
  application:
    name: songmm-ribbon-consumer
eureka: 
  client: 
    service-url: 
      defaultZoon: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
        
        
