server: 
  port: 8761
eureka: 
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZoon: http://song:song@localhost:8761/eureka
security:
  basic:
    enabled: true
  user:
    name: song
    password: song
