server:
  port: 7700
  
spring:
  application:
    name: kafka-producer
  cloud:
    config:
      name: eureka_client
      profile: dev
      label: master
      uri: http://localhost:8760/
      fail-fast: true
      discovery:
        enabled: true # 表示开启通过服务名来访问config-server
        service-id: config-server # 表示注册中心config-server的服务名
spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1:9092
  zk-nodes: 127.0.0.1:2181
  minPartitionCount: 1
  autoCreateTopics: true
  autoAddPartitions: true
spring.cloud.stream.bindings.producerA:
  destination: topic_a
  group: group-1
  consumer:
    concurrency: 1
    partitioned: false
spring.cloud.stream.bindings.producerB:
  destination: topic_b
  group: group-1
  consumer:
    concurrency: 1
    partitioned: false
spring.cloud.stream.bindings.consumerA:
  destination: topic_a
  producer: 
    partitionCount: 1 
spring.cloud.stream.bindings.consumerB:
  destination: topic_b
  producer: 
    partitionCount: 1    
